{% set name = "acl" %}
{% set version = "2.3.2" %}

package:
  name: lib{{ name }}
  version: {{ version }}

source:
  url: http://download.savannah.gnu.org/releases/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: 97203a72cae99ab89a067fe2210c1cbf052bc492b479eca7d226d9830883b0bd

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('libacl', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - autoconf
    - make
  host:
    - attr

test:
  commands:
    - test -f ${PREFIX}/include/sys/acl.h

about:
  home: https://savannah.nongnu.org/projects/acl
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: doc/COPYING
  summary: Commands for Manipulating POSIX Access Control Lists
  description: Commands for Manipulating POSIX Access Control Lists
  doc_url: https://savannah.nongnu.org/projects/acl
  dev_url: https://savannah.nongnu.org/git/?group=acl

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/47182
    reason: Dependency for systemd
  recipe-maintainers:
    - ianaobi
    - Tobias-Fischer
    - wolfv
